/*     */ package lumine.xikage.mythicmobs.skills.placeholders;
/*     */ 
/*     */ import io.lumine.xikage.mythicmobs.skills.placeholders.Placeholder;
/*     */ import io.lumine.xikage.mythicmobs.skills.placeholders.PlaceholderManager;
/*     */ import java.util.HashMap;
/*     */ import java.util.Map;
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ class PlaceholderTree
/*     */ {
/*     */   public void setPlaceholder(Placeholder placeholder) {
/* 244 */     this.placeholder = placeholder; } public void setSubPlaceholders(Map<String, PlaceholderTree> subPlaceholders) { this.subPlaceholders = subPlaceholders; } public boolean equals(Object o) { if (o == this) return true;  if (!(o instanceof PlaceholderTree)) return false;  PlaceholderTree other = (PlaceholderTree)o; if (!other.canEqual(this)) return false;  Object this$placeholder = getPlaceholder(), other$placeholder = other.getPlaceholder(); if ((this$placeholder == null) ? (other$placeholder != null) : !this$placeholder.equals(other$placeholder)) return false;  Object<String, PlaceholderTree> this$subPlaceholders = (Object<String, PlaceholderTree>)getSubPlaceholders(), other$subPlaceholders = (Object<String, PlaceholderTree>)other.getSubPlaceholders(); return !((this$subPlaceholders == null) ? (other$subPlaceholders != null) : !this$subPlaceholders.equals(other$subPlaceholders)); } protected boolean canEqual(Object other) { return other instanceof PlaceholderTree; } public int hashCode() { int PRIME = 59; result = 1; Object $placeholder = getPlaceholder(); result = result * 59 + (($placeholder == null) ? 43 : $placeholder.hashCode()); Object<String, PlaceholderTree> $subPlaceholders = (Object<String, PlaceholderTree>)getSubPlaceholders(); return result * 59 + (($subPlaceholders == null) ? 43 : $subPlaceholders.hashCode()); } public String toString() { return "PlaceholderManager.PlaceholderTree(placeholder=" + getPlaceholder() + ", subPlaceholders=" + getSubPlaceholders() + ")"; }
/*     */   
/* 246 */   private Placeholder placeholder = null; public Placeholder getPlaceholder() { return this.placeholder; }
/* 247 */    private Map<String, PlaceholderTree> subPlaceholders = new HashMap<>(); public Map<String, PlaceholderTree> getSubPlaceholders() { return this.subPlaceholders; }
/*     */ 
/*     */ }


/* Location:              D:\JavaProject\RidePet\libs\MythicMobsAPI\!\lumine\xikage\mythicmobs\skills\placeholders\PlaceholderManager$PlaceholderTree.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.1.3
 */