/*     */ package lumine.xikage.mythicmobs.skills.placeholders;
/*     */ 
/*     */ import io.lumine.xikage.mythicmobs.skills.placeholders.Placeholder;
/*     */ import io.lumine.xikage.mythicmobs.skills.placeholders.PlaceholderManager;
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ public class PlaceholderEntry
/*     */ {
/*     */   private final Placeholder placeholder;
/*     */   private final String arg;
/*     */   
/*     */   public boolean equals(Object o) {
/* 250 */     if (o == this) return true;  if (!(o instanceof PlaceholderEntry)) return false;  PlaceholderEntry other = (PlaceholderEntry)o; if (!other.canEqual(this)) return false;  Object this$placeholder = getPlaceholder(), other$placeholder = other.getPlaceholder(); if ((this$placeholder == null) ? (other$placeholder != null) : !this$placeholder.equals(other$placeholder)) return false;  Object this$arg = getArg(), other$arg = other.getArg(); return !((this$arg == null) ? (other$arg != null) : !this$arg.equals(other$arg)); } protected boolean canEqual(Object other) { return other instanceof PlaceholderEntry; } public int hashCode() { int PRIME = 59; result = 1; Object $placeholder = getPlaceholder(); result = result * 59 + (($placeholder == null) ? 43 : $placeholder.hashCode()); Object $arg = getArg(); return result * 59 + (($arg == null) ? 43 : $arg.hashCode()); } public String toString() { return "PlaceholderManager.PlaceholderEntry(placeholder=" + getPlaceholder() + ", arg=" + getArg() + ")"; }
/*     */   
/* 252 */   public Placeholder getPlaceholder() { return this.placeholder; } public String getArg() {
/* 253 */     return this.arg;
/*     */   }
/*     */   public PlaceholderEntry(Placeholder p, String a) {
/* 256 */     this.placeholder = p;
/* 257 */     this.arg = (a != null) ? a : "null";
/*     */   }
/*     */ }


/* Location:              D:\JavaProject\RidePet\libs\MythicMobsAPI\!\lumine\xikage\mythicmobs\skills\placeholders\PlaceholderManager$PlaceholderEntry.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.1.3
 */